version: '3.8'

services:
  web:
    build:
      context: .
      args:
        EXPOSE_PORT: ${EXPOSE_PORT}
        HOST: ${HOST}
        PORT: ${PORT}
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    environment:
      - FLASK_ENV=development # Set environment variables for Flask app (development, production)
      - TZ=America/Halifax # Set timezone for container
    env_file:
      - .env
